# Generated by Django 4.1.4 on 2023-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
