# Generated by Django 4.1.4 on 2023-09-08 19:28

import base_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0005_alter_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=base_api.models.upload_to),
        ),
    ]
