# Generated by Django 4.1.4 on 2023-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0006_remove_item_photo_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
