# Generated by Django 4.1.4 on 2023-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
